# Generated by Django 4.1.5 on 2023-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('exp_type', models.CharField(choices=[('hatching', 'Hatching'), ('traveling', 'Traveling'), ('feed', 'Feed'), ('medicines', 'Medicines'), ('equipments', 'Equipments'), ('others', 'Others')], default='others', max_length=10)),
                ('exp_description', models.TextField(blank=True, null=True)),
                ('exp_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exp_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
