# Generated by Django 4.1.5 on 2023-03-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expenses_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_type',
            field=models.CharField(choices=[('hatching', 'Hatching'), ('traveling', 'Traveling'), ('chick_feed', 'Chick Feed'), ('grower_feed', 'Grower Feed'), ('layer_feed', 'Layer Feed'), ('medicines', 'Medicines'), ('equipments', 'Equipments'), ('others', 'Others')], default='others', max_length=15),
        ),
    ]
