# Generated by Django 4.1.5 on 2023-03-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_expenses_exp_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ('-exp_created',)},
        ),
    ]
