# Generated by Django 4.1.5 on 2023-03-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_type',
            field=models.CharField(choices=[('products', 'Products'), ('hatching', 'Hatching'), ('traveling', 'Traveling'), ('chick_feed', 'Chick Feed'), ('grower_feed', 'Grower Feed'), ('layer_feed', 'Layer Feed'), ('medicines', 'Medicines'), ('workers', 'Workers'), ('rent', 'Rent'), ('others', 'Others')], default='others', max_length=15),
        ),
    ]
