# Generated by Django 4.1.5 on 2023-03-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_expenses_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='exp_date',
        ),
    ]
