# Generated by Django 4.1.5 on 2023-03-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_expenses_exp_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
