# Generated by Django 4.1.5 on 2023-03-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
